language: node_js
sudo: required
dist: trusty

node_js:
- '8.9.4'
branches:
  only:
    - master
    - develop
addons:
  firefox: latest
before_script:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
jobs:
  include:
    - env: "MODE=lint"
    - env: "MODE=aot"
    - env: "MODE=release"
    - env: "MODE=unit-test"
    - env: "MODE=a11y"
